wandb_version: 1

project_name:
  desc: null
  value: AudioFocus
entity:
  desc: null
  value: hyeonsio
group_name:
  desc: null
  value: tune_libri2mix_linear_titanet
exp_name:
  desc: null
  value: lr0.01_wd0.001
device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 1
dataset:
  desc: null
  value:
    type: Libri2Mix
    dataloader:
      batch_size: 32
      num_workers: 4
      pin_memory: true
model:
  desc: null
  value:
    asr:
      type: whisper
      opt: tiny.en
    filter:
      type: linear
      in_dim: 192
      hidden_dim: 288
      out_dim: 384
    speaker:
      type: titanet
      opt: nvidia/speakerverification_en_titanet_large
vanilla:
  desc: null
  value:
    asr:
      type: whisper
      opt: tiny.en
    filter:
      type: base
    speaker:
      type: base
trainer:
  desc: null
  value:
    seed: 1
    use_amp: true
    base_epochs: 100
    clip_grad_norm: 0.5
    optimizer_type: adamw
    optimizer:
      lr: 0.01
      weight_decay: 0.001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
    scheduler:
      first_cycle_steps: null
      cycle_mult: 1.0
      max_lr: 0.01
      min_lr: 0.01
      warmup_lr: 0.0
      warmup_ratio: 0.1
      gamma: 1.0
    log_every: 1000
    base_test_every: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711546927.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 100
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 100
      - 103
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.4
      6: 4.39.1
      8:
      - 5
      13: linux-x86_64
